schema_version = "1.0.0"
id = "b3d_ui_langloop"
name = "B3D UI Language Loop"
tagline = "Quickly cycle Blender interface languages with a shortcut"
version = "1.0.3"
type = "add-on"
tags = ["User Interface"]
blender_version_min = "5.0.0"
maintainer = "柚桑 / 楊景貴 / issac <issacsopp@gmail.com>"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/issacmaya/b3d-ui-langloop"
copyright = ["2026 issac"]